### ISSUE TITLE
Annotated data not sufficient to replicate

### ISSUE THREAD

**Issue by frankier** [PeliconA/news_sentiment_tool_embeddia#2]
Hi again! The data deposited at https://www.clarin.si/repository/xmlui/handle/11356/1342 does not contain the text of the annotated articles, nor the original Likert scale ratings. This is contrasted with SentiNews 1.0 https://www.clarin.si/repository/xmlui/handle/11356/1110 which does contain it. Is there a reason for this omission? Is it possible to replicate your work without this data?

**Comment by PeliconA** [comment]
Hi!
Unfortunately, we were unable to obtain permission to post the Croatian news dataset to the public but we were allowed to post only labels and links to the original articles. That means that the only way to use this dataset is to scrape the articles one by one from the URL's.
Note also that the results in the article are the results of cross-validation. The model in this repository was retrained on the whole dataset using the methods described in the article for the purposes of the Embeddia Hackashop.

**Comment by frankier** [comment]
Okay. I'm not a lawyer, but under some circumstances there's the possibility under EU law of publishing text for the purpose of text and data mining. It might be worth considering. http://copyrightblog.kluweriplaw.com/2019/07/24/the-new-copyright-directive-text-and-data-mining-articles-3-and-4/
